'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1318
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace QueuerServiceProxy
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/RDdotNet.TeamFoundation.Events")>  _
    Public Enum EventTypes As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Unknown = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AclChangedEven = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Branchmovedevent = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        BuildCompletionEvent = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        BuildStatusChangeEvent = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        CommonStructureChangedEvent = 5
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DataChangedEvent = 6
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        IdentityChangedEvent = 7
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        IdentityCreatedEvent = 8
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        IdentityDeletedEvent = 9
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        MembershipChangedEvent = 10
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        WorkItemChangedEvent = 11
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        CheckinEvent = 12
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/RDdotNet.TeamFoundation.Services.DataCont"& _ 
        "racts"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Subscription
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AddressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EventTypeField As QueuerServiceProxy.EventTypes
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IDField As Integer
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Address() As String
            Get
                Return Me.AddressField
            End Get
            Set
                Me.AddressField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EventType() As QueuerServiceProxy.EventTypes
            Get
                Return Me.EventTypeField
            End Get
            Set
                Me.EventTypeField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID() As Integer
            Get
                Return Me.IDField
            End Get
            Set
                Me.IDField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Notification/03", ConfigurationName:="QueuerServiceProxy.INotification")>  _
    Public Interface INotification
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface INotificationChannel
        Inherits QueuerServiceProxy.INotification, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class NotificationClient
        Inherits System.ServiceModel.ClientBase(Of QueuerServiceProxy.INotification)
        Implements QueuerServiceProxy.INotification
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://schemas.ml.com/TeamFoundation/2005/06/Services/SubscriptionAdmin", ConfigurationName:="QueuerServiceProxy.ISubscriptions", CallbackContract:=GetType(QueuerServiceProxy.ISubscriptionsCallback))>  _
    Public Interface ISubscriptions
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://schemas.ml.com/TeamFoundation/2005/06/Services/SubscriptionAdmin/ISubscrip"& _ 
            "tions/AddSubscriptions")>  _
        Sub AddSubscriptions(ByVal ServiceUrl As String, ByVal EventType As QueuerServiceProxy.EventTypes)
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://schemas.ml.com/TeamFoundation/2005/06/Services/SubscriptionAdmin/ISubscrip"& _ 
            "tions/RemoveSubscriptions")>  _
        Sub RemoveSubscriptions(ByVal ServiceUrl As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.ml.com/TeamFoundation/2005/06/Services/SubscriptionAdmin/ISubscrip"& _ 
            "tions/GetSubscriptions", ReplyAction:="http://schemas.ml.com/TeamFoundation/2005/06/Services/SubscriptionAdmin/ISubscrip"& _ 
            "tions/GetSubscriptionsResponse")>  _
        Function GetSubscriptions() As QueuerServiceProxy.Subscription()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface ISubscriptionsCallback
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://schemas.ml.com/TeamFoundation/2005/06/Services/SubscriptionAdmin/ISubscrip"& _ 
            "tions/Updated")>  _
        Sub Updated(ByVal Subscriptions() As QueuerServiceProxy.Subscription)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface ISubscriptionsChannel
        Inherits QueuerServiceProxy.ISubscriptions, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class SubscriptionsClient
        Inherits System.ServiceModel.DuplexClientBase(Of QueuerServiceProxy.ISubscriptions)
        Implements QueuerServiceProxy.ISubscriptions
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext)
            MyBase.New(callbackInstance)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String)
            MyBase.New(callbackInstance, endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(callbackInstance, endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(callbackInstance, endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(callbackInstance, binding, remoteAddress)
        End Sub
        
        Public Sub AddSubscriptions(ByVal ServiceUrl As String, ByVal EventType As QueuerServiceProxy.EventTypes) Implements QueuerServiceProxy.ISubscriptions.AddSubscriptions
            MyBase.Channel.AddSubscriptions(ServiceUrl, EventType)
        End Sub
        
        Public Sub RemoveSubscriptions(ByVal ServiceUrl As String) Implements QueuerServiceProxy.ISubscriptions.RemoveSubscriptions
            MyBase.Channel.RemoveSubscriptions(ServiceUrl)
        End Sub
        
        Public Function GetSubscriptions() As QueuerServiceProxy.Subscription() Implements QueuerServiceProxy.ISubscriptions.GetSubscriptions
            Return MyBase.Channel.GetSubscriptions
        End Function
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://schemas.ml.com/TeamFoundation/2007/04/Services/TeamServerAdmin/03", ConfigurationName:="QueuerServiceProxy.ITeamServers", CallbackContract:=GetType(QueuerServiceProxy.ITeamServersCallback))>  _
    Public Interface ITeamServers
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://schemas.ml.com/TeamFoundation/2007/04/Services/TeamServerAdmin/03/ITeamSer"& _ 
            "vers/AddServer")>  _
        Sub AddServer(ByVal TeamServerName As String, ByVal TeamServerUri As String)
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://schemas.ml.com/TeamFoundation/2007/04/Services/TeamServerAdmin/03/ITeamSer"& _ 
            "vers/RemoveServer")>  _
        Sub RemoveServer(ByVal TeamServerName As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.ml.com/TeamFoundation/2007/04/Services/TeamServerAdmin/03/ITeamSer"& _ 
            "vers/ServceUrl", ReplyAction:="http://schemas.ml.com/TeamFoundation/2007/04/Services/TeamServerAdmin/03/ITeamSer"& _ 
            "vers/ServceUrlResponse")>  _
        Function ServceUrl() As System.Uri
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.ml.com/TeamFoundation/2007/04/Services/TeamServerAdmin/03/ITeamSer"& _ 
            "vers/GetServers", ReplyAction:="http://schemas.ml.com/TeamFoundation/2007/04/Services/TeamServerAdmin/03/ITeamSer"& _ 
            "vers/GetServersResponse")>  _
        Function GetServers() As String()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface ITeamServersCallback
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://schemas.ml.com/TeamFoundation/2007/04/Services/TeamServerAdmin/03/ITeamSer"& _ 
            "vers/Updated")>  _
        Sub Updated(ByVal TeamServers() As String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface ITeamServersChannel
        Inherits QueuerServiceProxy.ITeamServers, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class TeamServersClient
        Inherits System.ServiceModel.DuplexClientBase(Of QueuerServiceProxy.ITeamServers)
        Implements QueuerServiceProxy.ITeamServers
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext)
            MyBase.New(callbackInstance)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String)
            MyBase.New(callbackInstance, endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(callbackInstance, endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(callbackInstance, endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(callbackInstance, binding, remoteAddress)
        End Sub
        
        Public Sub AddServer(ByVal TeamServerName As String, ByVal TeamServerUri As String) Implements QueuerServiceProxy.ITeamServers.AddServer
            MyBase.Channel.AddServer(TeamServerName, TeamServerUri)
        End Sub
        
        Public Sub RemoveServer(ByVal TeamServerName As String) Implements QueuerServiceProxy.ITeamServers.RemoveServer
            MyBase.Channel.RemoveServer(TeamServerName)
        End Sub
        
        Public Function ServceUrl() As System.Uri Implements QueuerServiceProxy.ITeamServers.ServceUrl
            Return MyBase.Channel.ServceUrl
        End Function
        
        Public Function GetServers() As String() Implements QueuerServiceProxy.ITeamServers.GetServers
            Return MyBase.Channel.GetServers
        End Function
    End Class
End Namespace
