'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection
Imports System.Runtime.Serialization

Namespace DataAccess
	
	<System.Data.Linq.Mapping.DatabaseAttribute(Name:="Heat")>  _
	Partial Friend Class HeatDataContext
		Inherits System.Data.Linq.DataContext
		
		Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnCreated()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New(Global.Hinshelwood.TeamFoundation.WorkItemTracking.My.MySettings.Default.HeatConnectionString, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As String)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As System.Data.IDbConnection)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
			MyBase.New(connection, mappingSource)
			OnCreated
		End Sub
		
		<FunctionAttribute(Name:="dbo.UpdateJournal")>  _
		Public Function UpdateJournal(<Parameter(Name:="CallId", DbType:="Int")> ByVal callId As System.Nullable(Of Integer), <Parameter(Name:="EntryText", DbType:="Text")> ByVal entryText As String, <Parameter(Name:="UserId", DbType:="VarChar(96)")> ByVal userId As String, <Parameter(Name:="Duration", DbType:="Int")> ByVal duration As System.Nullable(Of Integer)) As Integer
			Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), callId, entryText, userId, duration)
			Return CType(result.ReturnValue,Integer)
		End Function
	End Class
End Namespace
