<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:i0="http://schema.rddotnet.com/2007/08/TFSEventHandler/EventReciever" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://tempuri.org/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:import namespace="http://schema.rddotnet.com/2007/08/TFSEventHandler/EventReciever" location="http://localhost:31634/DecissionService/EventReciever.asmx?wsdl=wsdl1" />
  <wsdl:types />
  <wsdl:service name="EventReciever">
    <wsdl:port name="EventReciever" binding="i0:EventReciever">
      <soap:address location="http://localhost:31634/DecissionService/EventReciever.asmx" />
    </wsdl:port>
    <wsdl:port name="EventReciever1" binding="i0:EventReciever1">
      <soap12:address location="http://localhost:31634/DecissionService/EventReciever.asmx" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>