'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace EventHandlerService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/RDdotNet.TeamFoundation.Services.DataCont"& _ 
        "racts"),  _
     System.SerializableAttribute()>  _
    Partial Public Class AssemblyItem
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EventHandlersField() As EventHandlerService.EventHandlerItem
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IDField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LocationField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As System.Reflection.AssemblyName
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EventHandlers() As EventHandlerService.EventHandlerItem()
            Get
                Return Me.EventHandlersField
            End Get
            Set
                Me.EventHandlersField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID() As System.Guid
            Get
                Return Me.IDField
            End Get
            Set
                Me.IDField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Location() As String
            Get
                Return Me.LocationField
            End Get
            Set
                Me.LocationField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As System.Reflection.AssemblyName
            Get
                Return Me.NameField
            End Get
            Set
                Me.NameField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/RDdotNet.TeamFoundation.Services.DataCont"& _ 
        "racts"),  _
     System.SerializableAttribute()>  _
    Partial Public Class EventHandlerItem
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EventTypeField As EventHandlerService.EventTypes
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HandlerTypeField As System.Type
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EventType() As EventHandlerService.EventTypes
            Get
                Return Me.EventTypeField
            End Get
            Set
                Me.EventTypeField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HandlerType() As System.Type
            Get
                Return Me.HandlerTypeField
            End Get
            Set
                Me.HandlerTypeField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/RDdotNet.TeamFoundation")>  _
    Public Enum EventTypes As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Unknown = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AclChangedEven = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Branchmovedevent = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        BuildCompletionEvent = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        BuildStatusChangeEvent = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        CommonStructureChangedEvent = 5
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DataChangedEvent = 6
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        IdentityChangedEvent = 7
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        IdentityCreatedEvent = 8
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        IdentityDeletedEvent = 9
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        MembershipChangedEvent = 10
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        WorkItemChangedEvent = 11
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        CheckinEvent = 12
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/System.Reflection.Cache"),  _
     System.SerializableAttribute()>  _
    Partial Public Class InternalCache
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private m_cacheField() As EventHandlerService.InternalCacheItem
        
        Private m_numItemsField As Integer
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property m_cache() As EventHandlerService.InternalCacheItem()
            Get
                Return Me.m_cacheField
            End Get
            Set
                Me.m_cacheField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property m_numItems() As Integer
            Get
                Return Me.m_numItemsField
            End Get
            Set
                Me.m_numItemsField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/System.Reflection.Cache"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.AssemblyItem)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.EventHandlerItem())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.EventHandlerItem)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.AssemblyManaifest)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.AssemblyItem())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.SubscriptionInfo)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Reflection.MemberInfo)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Reflection.AssemblyName)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.WorkItemChangedEvent)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.ChangeTypes)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.ChangedFieldsType)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.IntegerField())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.IntegerField)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.StringField())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.StringField)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.CoreFieldsType)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.TextField())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.TextField)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.TFSIdentity)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.CheckinEvent)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.EventTypes)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.InternalCache)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.InternalCacheItem())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.CacheObjType)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(String())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Object())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Type))>  _
    Partial Public Structure InternalCacheItem
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private KeyField As EventHandlerService.CacheObjType
        
        Private ValueField As Object
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Key() As EventHandlerService.CacheObjType
            Get
                Return Me.KeyField
            End Get
            Set
                Me.KeyField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Value() As Object
            Get
                Return Me.ValueField
            End Get
            Set
                Me.ValueField = value
            End Set
        End Property
    End Structure
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/RDdotNet.TeamFoundation.Services.DataCont"& _ 
        "racts"),  _
     System.SerializableAttribute()>  _
    Partial Public Class AssemblyManaifest
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AssemblysField() As EventHandlerService.AssemblyItem
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VersionField As Integer
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Assemblys() As EventHandlerService.AssemblyItem()
            Get
                Return Me.AssemblysField
            End Get
            Set
                Me.AssemblysField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Version() As Integer
            Get
                Return Me.VersionField
            End Get
            Set
                Me.VersionField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/TeamFoundation/2005/06/Services/Notification/03"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SubscriptionInfo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ClassificationField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SubscriberField As String
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Classification() As String
            Get
                Return Me.ClassificationField
            End Get
            Set
                Me.ClassificationField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID() As String
            Get
                Return Me.IDField
            End Get
            Set
                Me.IDField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Subscriber() As String
            Get
                Return Me.SubscriberField
            End Get
            Set
                Me.SubscriberField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class WorkItemChangedEvent
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private addedFilesField() As String
        
        Private addedRelationsField() As String
        
        Private addedResourceLinksField() As String
        
        Private areaPathField As String
        
        Private changeTypeField As EventHandlerService.ChangeTypes
        
        Private changedFieldsField As EventHandlerService.ChangedFieldsType
        
        Private changedRelationsField() As String
        
        Private changedResourceLinksField() As String
        
        Private changerSidField As String
        
        Private coreFieldsField As EventHandlerService.CoreFieldsType
        
        Private deletedFilesField() As String
        
        Private deletedRelationsField() As String
        
        Private deletedResourceLinksField() As String
        
        Private displayUrlField As String
        
        Private portfolioProjectField As String
        
        Private projectNodeIdField As String
        
        Private subscriberField As String
        
        Private textFieldsField() As EventHandlerService.TextField
        
        Private timeZoneField As String
        
        Private timeZoneOffsetField As String
        
        Private titleField As String
        
        Private workItemTitleField As String
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property addedFiles() As String()
            Get
                Return Me.addedFilesField
            End Get
            Set
                Me.addedFilesField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property addedRelations() As String()
            Get
                Return Me.addedRelationsField
            End Get
            Set
                Me.addedRelationsField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property addedResourceLinks() As String()
            Get
                Return Me.addedResourceLinksField
            End Get
            Set
                Me.addedResourceLinksField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property areaPath() As String
            Get
                Return Me.areaPathField
            End Get
            Set
                Me.areaPathField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property changeType() As EventHandlerService.ChangeTypes
            Get
                Return Me.changeTypeField
            End Get
            Set
                Me.changeTypeField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property changedFields() As EventHandlerService.ChangedFieldsType
            Get
                Return Me.changedFieldsField
            End Get
            Set
                Me.changedFieldsField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property changedRelations() As String()
            Get
                Return Me.changedRelationsField
            End Get
            Set
                Me.changedRelationsField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property changedResourceLinks() As String()
            Get
                Return Me.changedResourceLinksField
            End Get
            Set
                Me.changedResourceLinksField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property changerSid() As String
            Get
                Return Me.changerSidField
            End Get
            Set
                Me.changerSidField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property coreFields() As EventHandlerService.CoreFieldsType
            Get
                Return Me.coreFieldsField
            End Get
            Set
                Me.coreFieldsField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property deletedFiles() As String()
            Get
                Return Me.deletedFilesField
            End Get
            Set
                Me.deletedFilesField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property deletedRelations() As String()
            Get
                Return Me.deletedRelationsField
            End Get
            Set
                Me.deletedRelationsField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property deletedResourceLinks() As String()
            Get
                Return Me.deletedResourceLinksField
            End Get
            Set
                Me.deletedResourceLinksField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property displayUrl() As String
            Get
                Return Me.displayUrlField
            End Get
            Set
                Me.displayUrlField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property portfolioProject() As String
            Get
                Return Me.portfolioProjectField
            End Get
            Set
                Me.portfolioProjectField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property projectNodeId() As String
            Get
                Return Me.projectNodeIdField
            End Get
            Set
                Me.projectNodeIdField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property subscriber() As String
            Get
                Return Me.subscriberField
            End Get
            Set
                Me.subscriberField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property textFields() As EventHandlerService.TextField()
            Get
                Return Me.textFieldsField
            End Get
            Set
                Me.textFieldsField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property timeZone() As String
            Get
                Return Me.timeZoneField
            End Get
            Set
                Me.timeZoneField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property timeZoneOffset() As String
            Get
                Return Me.timeZoneOffsetField
            End Get
            Set
                Me.timeZoneOffsetField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property title() As String
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property workItemTitle() As String
            Get
                Return Me.workItemTitleField
            End Get
            Set
                Me.workItemTitleField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/")>  _
    Public Enum ChangeTypes As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        [New] = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Change = 1
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ChangedFieldsType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private integerFieldsField() As EventHandlerService.IntegerField
        
        Private stringFieldsField() As EventHandlerService.StringField
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property integerFields() As EventHandlerService.IntegerField()
            Get
                Return Me.integerFieldsField
            End Get
            Set
                Me.integerFieldsField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property stringFields() As EventHandlerService.StringField()
            Get
                Return Me.stringFieldsField
            End Get
            Set
                Me.stringFieldsField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class IntegerField
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private nameField As String
        
        Private newValueField As Integer
        
        Private oldValueField As Integer
        
        Private referenceNameField As String
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property newValue() As Integer
            Get
                Return Me.newValueField
            End Get
            Set
                Me.newValueField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property oldValue() As Integer
            Get
                Return Me.oldValueField
            End Get
            Set
                Me.oldValueField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property referenceName() As String
            Get
                Return Me.referenceNameField
            End Get
            Set
                Me.referenceNameField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class StringField
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private nameField As String
        
        Private newValueField As String
        
        Private oldValueField As String
        
        Private referenceNameField As String
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property newValue() As String
            Get
                Return Me.newValueField
            End Get
            Set
                Me.newValueField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property oldValue() As String
            Get
                Return Me.oldValueField
            End Get
            Set
                Me.oldValueField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property referenceName() As String
            Get
                Return Me.referenceNameField
            End Get
            Set
                Me.referenceNameField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CoreFieldsType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private integerFieldsField() As EventHandlerService.IntegerField
        
        Private stringFieldsField() As EventHandlerService.StringField
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property integerFields() As EventHandlerService.IntegerField()
            Get
                Return Me.integerFieldsField
            End Get
            Set
                Me.integerFieldsField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property stringFields() As EventHandlerService.StringField()
            Get
                Return Me.stringFieldsField
            End Get
            Set
                Me.stringFieldsField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TextField
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private nameField As String
        
        Private referenceNameField As String
        
        Private valueField As String
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property referenceName() As String
            Get
                Return Me.referenceNameField
            End Get
            Set
                Me.referenceNameField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class TFSIdentity
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private urlField As String
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property url() As String
            Get
                Return Me.urlField
            End Get
            Set
                Me.urlField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.AssemblyItem)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.EventHandlerItem())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.EventHandlerItem)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.AssemblyManaifest)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.AssemblyItem())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.SubscriptionInfo)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Reflection.MemberInfo)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Reflection.AssemblyName)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.WorkItemChangedEvent)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.ChangeTypes)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.ChangedFieldsType)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.IntegerField())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.IntegerField)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.StringField())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.StringField)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.CoreFieldsType)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.TextField())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.TextField)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.TFSIdentity)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.EventTypes)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.InternalCache)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.InternalCacheItem())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.InternalCacheItem)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(EventHandlerService.CacheObjType)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(String())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(Object())),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(System.Type))>  _
    Partial Public Class CheckinEvent
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private allChangesIncludedField As Boolean
        
        Private artifactsField() As Object
        
        Private checkinInformationField() As Object
        
        Private checkinNotesField() As Object
        
        Private commentField As String
        
        Private committerField As String
        
        Private contentTitleField As String
        
        Private creationDateField As String
        
        Private noticeField As String
        
        Private numberField As Integer
        
        Private ownerField As String
        
        Private policyFailuresField() As Object
        
        Private policyOverrideCommentField As String
        
        Private subscriberField As String
        
        Private teamProjectField As String
        
        Private timeZoneField As String
        
        Private timeZoneOffsetField As String
        
        Private titleField As String
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property allChangesIncluded() As Boolean
            Get
                Return Me.allChangesIncludedField
            End Get
            Set
                Me.allChangesIncludedField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property artifacts() As Object()
            Get
                Return Me.artifactsField
            End Get
            Set
                Me.artifactsField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property checkinInformation() As Object()
            Get
                Return Me.checkinInformationField
            End Get
            Set
                Me.checkinInformationField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property checkinNotes() As Object()
            Get
                Return Me.checkinNotesField
            End Get
            Set
                Me.checkinNotesField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property comment() As String
            Get
                Return Me.commentField
            End Get
            Set
                Me.commentField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property committer() As String
            Get
                Return Me.committerField
            End Get
            Set
                Me.committerField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property contentTitle() As String
            Get
                Return Me.contentTitleField
            End Get
            Set
                Me.contentTitleField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property creationDate() As String
            Get
                Return Me.creationDateField
            End Get
            Set
                Me.creationDateField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property notice() As String
            Get
                Return Me.noticeField
            End Get
            Set
                Me.noticeField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property number() As Integer
            Get
                Return Me.numberField
            End Get
            Set
                Me.numberField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property owner() As String
            Get
                Return Me.ownerField
            End Get
            Set
                Me.ownerField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property policyFailures() As Object()
            Get
                Return Me.policyFailuresField
            End Get
            Set
                Me.policyFailuresField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property policyOverrideComment() As String
            Get
                Return Me.policyOverrideCommentField
            End Get
            Set
                Me.policyOverrideCommentField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property subscriber() As String
            Get
                Return Me.subscriberField
            End Get
            Set
                Me.subscriberField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property teamProject() As String
            Get
                Return Me.teamProjectField
            End Get
            Set
                Me.teamProjectField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property timeZone() As String
            Get
                Return Me.timeZoneField
            End Get
            Set
                Me.timeZoneField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property timeZoneOffset() As String
            Get
                Return Me.timeZoneOffsetField
            End Get
            Set
                Me.timeZoneOffsetField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property title() As String
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/System.Reflection.Cache")>  _
    Public Enum CacheObjType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        EmptyElement = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ParameterInfo = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        TypeName = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        RemotingData = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        SerializableAttribute = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        AssemblyName = 5
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ConstructorInfo = 6
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        FieldType = 7
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        FieldName = 8
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DefaultMember = 9
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://schemas.ml.com/TeamFoundation/2005/06/Services/TFSEventHandler/HandlerAdmi"& _ 
        "n", ConfigurationName:="EventHandlerService.IHandlers", CallbackContract:=GetType(EventHandlerService.IHandlersCallback))>  _
    Public Interface IHandlers
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://schemas.ml.com/TeamFoundation/2005/06/Services/TFSEventHandler/HandlerAdmi"& _ 
            "n/IHandlers/AddAssembly")>  _
        Sub AddAssembly(ByVal AssemblyItem As EventHandlerService.AssemblyItem)
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://schemas.ml.com/TeamFoundation/2005/06/Services/TFSEventHandler/HandlerAdmi"& _ 
            "n/IHandlers/AddAssemblyDirect")>  _
        Sub AddAssemblyDirect(ByVal AssemblyBytes() As Byte)
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://schemas.ml.com/TeamFoundation/2005/06/Services/TFSEventHandler/HandlerAdmi"& _ 
            "n/IHandlers/RemoveAssembly")>  _
        Sub RemoveAssembly(ByVal ID As Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.ml.com/TeamFoundation/2005/06/Services/TFSEventHandler/HandlerAdmi"& _ 
            "n/IHandlers/GetAssemblys", ReplyAction:="http://schemas.ml.com/TeamFoundation/2005/06/Services/TFSEventHandler/HandlerAdmi"& _ 
            "n/IHandlers/GetAssemblysResponse")>  _
        Function GetAssemblys() As EventHandlerService.AssemblyManaifest
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.ml.com/TeamFoundation/2005/06/Services/TFSEventHandler/HandlerAdmi"& _ 
            "n/IHandlers/GetAssemblyItem", ReplyAction:="http://schemas.ml.com/TeamFoundation/2005/06/Services/TFSEventHandler/HandlerAdmi"& _ 
            "n/IHandlers/GetAssemblyItemResponse")>  _
        Function GetAssemblyItem(ByVal AssemblyBytes() As Byte) As EventHandlerService.AssemblyItem
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.ml.com/TeamFoundation/2005/06/Services/TFSEventHandler/HandlerAdmi"& _ 
            "n/IHandlers/ValidateAssembly", ReplyAction:="http://schemas.ml.com/TeamFoundation/2005/06/Services/TFSEventHandler/HandlerAdmi"& _ 
            "n/IHandlers/ValidateAssemblyResponse")>  _
        Function ValidateAssembly(ByVal AssemblyItem As EventHandlerService.AssemblyItem) As Boolean
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface IHandlersCallback
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://schemas.ml.com/TeamFoundation/2005/06/Services/TFSEventHandler/HandlerAdmi"& _ 
            "n/IHandlers/Updated")>  _
        Sub Updated(ByVal AssemblyManaifest As EventHandlerService.AssemblyManaifest)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface IHandlersChannel
        Inherits EventHandlerService.IHandlers, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class HandlersClient
        Inherits System.ServiceModel.DuplexClientBase(Of EventHandlerService.IHandlers)
        Implements EventHandlerService.IHandlers
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext)
            MyBase.New(callbackInstance)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String)
            MyBase.New(callbackInstance, endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(callbackInstance, endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(callbackInstance, endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(callbackInstance, binding, remoteAddress)
        End Sub
        
        Public Sub AddAssembly(ByVal AssemblyItem As EventHandlerService.AssemblyItem) Implements EventHandlerService.IHandlers.AddAssembly
            MyBase.Channel.AddAssembly(AssemblyItem)
        End Sub
        
        Public Sub AddAssemblyDirect(ByVal AssemblyBytes() As Byte) Implements EventHandlerService.IHandlers.AddAssemblyDirect
            MyBase.Channel.AddAssemblyDirect(AssemblyBytes)
        End Sub
        
        Public Sub RemoveAssembly(ByVal ID As Integer) Implements EventHandlerService.IHandlers.RemoveAssembly
            MyBase.Channel.RemoveAssembly(ID)
        End Sub
        
        Public Function GetAssemblys() As EventHandlerService.AssemblyManaifest Implements EventHandlerService.IHandlers.GetAssemblys
            Return MyBase.Channel.GetAssemblys
        End Function
        
        Public Function GetAssemblyItem(ByVal AssemblyBytes() As Byte) As EventHandlerService.AssemblyItem Implements EventHandlerService.IHandlers.GetAssemblyItem
            Return MyBase.Channel.GetAssemblyItem(AssemblyBytes)
        End Function
        
        Public Function ValidateAssembly(ByVal AssemblyItem As EventHandlerService.AssemblyItem) As Boolean Implements EventHandlerService.IHandlers.ValidateAssembly
            Return MyBase.Channel.ValidateAssembly(AssemblyItem)
        End Function
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="EventHandlerService.IEvents")>  _
    Public Interface IEvents
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://tempuri.org/IEvents/RaiseWorkItemChangedEvent")>  _
        Sub RaiseWorkItemChangedEvent(ByVal [Event] As EventHandlerService.WorkItemChangedEvent, ByVal EventIdentity As EventHandlerService.TFSIdentity, ByVal SubscriptionInfo As EventHandlerService.SubscriptionInfo)
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://tempuri.org/IEvents/RaiseCheckinEvent")>  _
        Sub RaiseCheckinEvent(ByVal [Event] As EventHandlerService.CheckinEvent, ByVal EventIdentity As EventHandlerService.TFSIdentity, ByVal SubscriptionInfo As EventHandlerService.SubscriptionInfo)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface IEventsChannel
        Inherits EventHandlerService.IEvents, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class EventsClient
        Inherits System.ServiceModel.ClientBase(Of EventHandlerService.IEvents)
        Implements EventHandlerService.IEvents
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub RaiseWorkItemChangedEvent(ByVal [Event] As EventHandlerService.WorkItemChangedEvent, ByVal EventIdentity As EventHandlerService.TFSIdentity, ByVal SubscriptionInfo As EventHandlerService.SubscriptionInfo) Implements EventHandlerService.IEvents.RaiseWorkItemChangedEvent
            MyBase.Channel.RaiseWorkItemChangedEvent([Event], EventIdentity, SubscriptionInfo)
        End Sub
        
        Public Sub RaiseCheckinEvent(ByVal [Event] As EventHandlerService.CheckinEvent, ByVal EventIdentity As EventHandlerService.TFSIdentity, ByVal SubscriptionInfo As EventHandlerService.SubscriptionInfo) Implements EventHandlerService.IEvents.RaiseCheckinEvent
            MyBase.Channel.RaiseCheckinEvent([Event], EventIdentity, SubscriptionInfo)
        End Sub
    End Class
End Namespace
